#' @title plot.BINDetect.volcano
#'
#' @description
#' Function to replot the volcano plot of differential motifs (footprints) as generated by BINDetect.
#'
#'
#' @param results Path to the TOBIAS BINDetect results table, e.g. \code{bindetect_results.txt}, or a corresponding data.frame.
#' @param motif.pattern String of the regular expression indicating the pattern to remove from the motif ID. Default: \code{"_(MOUSE|HUMAN)[.]H[0-9]*MO"}.
#' @param right.color String indicating the color to use for the differential motifs in the right side (positive difference) of the plot. Default: \code{"indianred"}.
#' @param left.color String indicating the color to use for the differential motifs in the left side (negative difference) of the plot. Default: \code{"steelblue"}.
#' @param ns.color String indicating the color to use for the non-significant motifs of the plot. Default: \code{"gray30"}.
#' @param points.transparency Numeric value between 0-1 indicating the transparency (alpha) of the dots in the volcano. Default: \code{0.5}.
#' @param add.signif.lables Logical value indicating whether differential motifs should be labelled. Default: \code{TRUE}.
#' @param labels.min.segment.length Numeric value indicating the minimum length of the line connecting the motif labels and the corresponding dot (passed to \code{ggrepel}). Default: \code{0}, segment always present.
#' @param labels.repel.force Numeric value indicated the force of repulsion between overlapping text labels (passed to \code{ggrepel}). Default: \code{10}.
#' @param labels.max.overlaps Numeric value indicating of maximum labels overlapping allowed (passed to \code{ggrepel}). Default: \code{100}.
#' @param extra.labels Vector of other motifs to display, retrospectively by their significance. Default: \code{"none"}.
#'
#' @return A ggplot object.
#'
#' @export plot.BINDetect.volcano
#'
#'
#'
#'
plot.BINDetect.volcano =
  function(results,
           motif.pattern = "_(MOUSE|HUMAN)[.]H[0-9]*MO",
           right.color = "indianred",
           left.color = "steelblue",
           ns.color = "gray30",
           points.transparency = 0.5,
           labels.min.segment.length = 0,
           add.signif.lables = TRUE,
           labels.repel.force = 10,
           labels.max.overlaps = 100,
           extra.labels = "none") {

    # Libs
    require(ggplot2)
    require(dplyr)
    if (add.signif.lables == TRUE){require(ggrepel)}

    # Read table if required
    if ("character" %in% class(results)) {
      results = dplyr::mutate(read.delim(results, h=T), motif_id = gsub(motif.pattern, "",motif_id))
    } else {
      results = as.data.frame(results)
    }

    # Get conditions names
    condition.A = gsub("_bound", "", colnames(results)[7])
    condition.B = gsub("_bound", "", colnames(results)[9])
    title = paste(condition.A, "vs", condition.B)

    # Standardize table col names
    colnames(results)[10] = "change"
    colnames(results)[11] = "pvalue"
    colnames(results)[12] = "signif"

    # Add Factor column for points colors
    results =
      dplyr::mutate(results,
                    diff.status = factor(ifelse(signif == "True" | signif == T,
                                                yes = ifelse(sign(change) == 1,
                                                             yes = paste("Higher in", condition.A),
                                                             no = paste("Higher in", condition.B)),
                                                no = "NS"),
                                         levels = c(paste("Higher in", condition.B),
                                                    paste("Higher in", condition.A),
                                                    "NS")))

    # Define colors
    colors = c(left.color, right.color, ns.color)
    names(colors) = c(paste("Higher in", condition.B),
                      paste("Higher in", condition.A),
                      "NS")


    # Generate the base plot
    plot =
      ggplot() +
      geom_point(data = results,
                 aes(x = change,
                     y = -log10(pvalue),
                     color = diff.status,
                     size = abs(change)),
                 stroke = NA,
                 alpha = points.transparency) +
      scale_color_manual(values = colors, name = "Differential binding status", drop = FALSE) +
      scale_size_continuous(name = "|Differential binding score|") +
      ggtitle(title) +
      ylab("-log~10~(*P*-value)") +
      xlab(paste0("Differential binding score [", condition.A, " - ", condition.B, "]")) +
      theme_classic() +
      theme(axis.title.y = ggtext::element_markdown(color = "black"),
            axis.text = ggtext::element_markdown(color = "black"),
            plot.title = element_text(hjust = 0.5),
            axis.ticks = element_line(color = "black"))

    # make plot simmetric
    # get the x-range max
    x.max = max(abs(ggplot_build(plot)$layout$panel_params[[1]]$x.range))

    plot = plot + xlim(c(-1,1) * x.max)



    if (add.signif.lables == TRUE) {
      plot =
        plot +
        geom_text_repel(data = results %>% filter(diff.status != "NS" | motif_id %in% extra.labels),
                        mapping = aes(x = change,
                                      y = -log10(pvalue),
                                      label = motif_id,
                                      color = diff.status),
                        show.legend = F,
                        min.segment.length = labels.min.segment.length,
                        force = labels.repel.force,
                        max.overlaps = labels.max.overlaps)
    }

    return(plot)
  }
