#' @title read.multibigwigsummary
#'
#' @description Imports ".npz" files generated by \code{multiBigwigSummary} (\code{deepTools}).
#'
#' @param multibigwigsummary.file Path to a \code{".npz"} file generated by \code{multiBigwigSummary}.
#'
#' @importFrom reticulate import
#'
#' @return A matrix where each column is a sample and each row a genomic bin/region.
#'
#' @export read.multibigwigsummary


read.multibigwigsummary =
  function(multibigwigsummary.file) {

    np = reticulate::import("numpy")
    npz = np$load(multibigwigsummary.file)
    matrix = npz$f[[npz$files[1]]]
    colnames(matrix) = npz$f[[npz$files[2]]]

    return(matrix)
  }
