# This .yaml cofinguration file contains all variables used by the snakemake pipeline
# DO NOT CHANGE parameter names without changing it in Snakefile as well
# On the other hand, some parameter values have to be inevitably modifed
# **********************************************************************************************************************************

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ ESSENTIAL PARAMETERS @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
### 0. General parameters  =========================================================================================================
# 0.1. Project path
runs_directory: "/home/user/ATAC_test/00_runs/"
output_directory: "/home/user/ATAC_test/"

# 0.2 Input file extensions
fastq_extension: ".fastq.gz"
runs_suffix: ["_R1", "_R2"]

# 0.3. Genome and black-listed regions
blacklist_file: "/home/user/annotations/blacklist/hg38-blacklist.v2.bed" # look at https://github.com/Boyle-Lab/Blacklist/
genome_fasta: "/home/user/annotations/genomes/Hg38/Homo_sapiens.GRCh38_v102.dna.primary_assembly.fa"

# 0.4 Type of signal correction
perform_HMCan_correction: "False"
      # If 'True' the signal will be corrected for the presence of CNVs
      # and the peak calling will be performed by HMCan instead of MACS3 --> set the correct genomeSize paramater
      #
      # If 'False' the peak calling will be performed by MACS2 --> set the correct genomeSize paramater

# 0.5 Normalization paramaters (bamCoverage parameters)
effective_genomeSize: 2900338458
ignore_for_normalization: "X Y MT M KI270728.1 KI270727.1 KI270442.1 KI270729.1 GL000225.1 KI270743.1 GL000008.2 GL000009.2 KI270747.1 KI270722.1 GL000194.1 KI270742.1 GL000205.2 GL000195.1 KI270736.1 KI270733.1 GL000224.1 GL000219.1 KI270719.1 GL000216.2 KI270712.1 KI270706.1 KI270725.1 KI270744.1 KI270734.1 GL000213.1 GL000220.1 KI270715.1 GL000218.1 KI270749.1 KI270741.1 GL000221.1 KI270716.1 KI270731.1 KI270751.1 KI270750.1 KI270519.1 GL000214.1 KI270708.1 KI270730.1 KI270438.1 KI270737.1 KI270721.1 KI270738.1 KI270748.1 KI270435.1 GL000208.1 KI270538.1 KI270756.1 KI270739.1 KI270757.1 KI270709.1 KI270746.1 KI270753.1 KI270589.1 KI270726.1 KI270735.1 KI270711.1 KI270745.1 KI270714.1 KI270732.1 KI270713.1 KI270754.1 KI270710.1 KI270717.1 KI270724.1 KI270720.1 KI270723.1 KI270718.1 KI270317.1 KI270740.1 KI270755.1 KI270707.1 KI270579.1 KI270752.1 KI270512.1 KI270322.1 GL000226.1 KI270311.1 KI270366.1 KI270511.1 KI270448.1 KI270521.1 KI270581.1 KI270582.1 KI270515.1 KI270588.1 KI270591.1 KI270522.1 KI270507.1 KI270590.1 KI270584.1 KI270320.1 KI270382.1 KI270468.1 KI270467.1 KI270362.1 KI270517.1 KI270593.1 KI270528.1 KI270587.1 KI270364.1 KI270371.1 KI270333.1 KI270374.1 KI270411.1 KI270414.1 KI270510.1 KI270390.1 KI270375.1 KI270420.1 KI270509.1 KI270315.1 KI270302.1 KI270518.1 KI270530.1 KI270304.1 KI270418.1 KI270424.1 KI270417.1 KI270508.1 KI270303.1 KI270381.1 KI270529.1 KI270425.1 KI270396.1 KI270363.1 KI270386.1 KI270465.1 KI270383.1 KI270384.1 KI270330.1 KI270372.1 KI270548.1 KI270580.1 KI270387.1 KI270391.1 KI270305.1 KI270373.1 KI270422.1 KI270316.1 KI270338.1 KI270340.1 KI270583.1 KI270334.1 KI270429.1 KI270393.1 KI270516.1 KI270389.1 KI270466.1 KI270388.1 KI270544.1 KI270310.1 KI270412.1 KI270395.1 KI270376.1 KI270337.1 KI270335.1 KI270378.1 KI270379.1 KI270329.1 KI270419.1 KI270336.1 KI270312.1 KI270539.1 KI270385.1 KI270423.1 KI270392.1 KI270394.1"



# 0.6 Variant calling
call_variants: true
call_SNPs: true
call_indels: true
dbsnp_file: "/home/user/annotations/gatk/dbsnp/resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf"
  # download also the INDEX!!!
  # https://console.cloud.google.com/storage/browser/genomics-public-data/resources/broad/hg38/v0/
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@



### 1. FastQC  ---------------------------------------------------------------------------------------------------------------------
fastQC_threads: 2



### 2. Alignment and BAM generation parameters  ------------------------------------------------------------------------------------
bwa_threads: 8
mapQ_cutoff: 20
SAMtools_threads: 8
remove_duplicates: "true" # only "true" or "false"; the output name will be '*dedup*' if true, and '*mdup*' if false
PICARD_max_records_in_ram: 250000
PICARD_max_file_handles_for_read_ends_map: 4000



### 3. BAM reads Shifting (deeptools -> alignmentSieve)  ---------------------------------------------------------------------------
minFragmentLength: 0
maxFragmentLength: 0



### 4. Fragments size distribution (deeptools -> bamPEFragmentSize)  ---------------------------------------------------------------
plot_format: "pdf"
bamPEFragmentSize_threads: 6
max_fragment_length: 2000   # A value of 0 (the default) indicates to use twice the mean fragment length.
window_length: 1000



### 5. Scaling factor computation (deeptools -> multiBamSummary)  ------------------------------------------------------------------
multiBamSummary_threads: 6



### 6. lorenz curves (deeptools -> plotFingerprint)  ------------------------------------------------------------------
plotFingerprint_threads: 8
plotFingerprint_binSize: 500
plotFingerprint_sampledRegions: 500000
plotFingerprint_extra_parameters: ""




#$$$ ********************************** REQUIRED ONLY IF 'perform_HMCan_correction = "True"' ***************************************
### 7. HMcan parameters
# 7.1 General
HMCan_path: "/home/user/HMCan-master/src/HMCan"
HMCan_threads: 12
chromosome_sizes_file: "/home/user/UCSC/chrom.sizes/hg38.chrom.sizes"
reference_sample: "NA"  #This sample will be the reference for the normalization, indicate a sample basename (without R1/2 or fastq.gz)

# 7.2 HMCan config file --> see https://bitbucket.org/pyminer/hmcan/src/master/
format: "BAM"
GCIndex: "/home/user/HMCan-master/data/GC_profile_25KbWindow_Mapp100bp_hg38.cnp"
smallBinLength: 5
largeBinLength: 25000
pvalueThreshold: 0.001
mergeDistance: 0
iterationThreshold: 5
finalThreshold: 0
maxIter: 20
PrintWig: "False"
PrintPosterior: "True"
PrintBedGraph: "True"
CallPeaks: "True"
pairedEnds: " True"
Type: "ATAC-seq"
GCmergeDistance: 1000
RemoveDuplicates: "False" # Default "False" because already performed by PICARD, time saving
CNAnormalization: "True"
# ***********************************************************************************************************************************



#$$$ ********************************** REQUIRED ONLY IF 'perform_HMCan_correction = "False"' ***************************************
# -----------------------------------------------------------------------------------------------------------------------------------
### 8. Bam normalization, signal file creation, and peakCalling (***when HMcan is skipped***; perform_HMCan_correction: "False")
bigWig_binSize: 5
normalization_method: "RPGC"
bamCoverage_threads: 8

# 9. MACS3
genome_size_MACS: "hs"   # hs: 2.7e9    # mm: 1.87e9    # ce: 9e7   # dm: 1.2e8
FDR_cutoff: 0.01
call_summits: "True"
FRiP_threshold: 20 #%, only used to asign a good/bad label in the sample count summary file

# ***********************************************************************************************************************************



### 10. Samples comparison for overall variance extimation (--> multiBigwigSummary | plotPCA | plotCorrelation, from deeptools) ---------
binning_window_size: 10000 #bp
multiBigwigSummary_threads: 4
heatmap_color: "Blues"
zScore_heatmap_color: "seismic"    # The available options are: (see --> https://matplotlib.org/stable/tutorials/colors/colormaps.html)
                                   # ‘Accent’, ‘Blues’, ‘BrBG’, ‘BuGn’, ‘BuPu’, ‘CMRmap’, ‘Dark2’, ‘GnBu’, ‘Greens’, ‘Greys’,
                                   # ‘OrRd’, ‘Oranges’, ‘PRGn’, ‘Paired’, ‘Pastel1’, ‘Pastel2’, ‘PiYG’, ‘PuBu’, ‘PuBuGn’, ‘PuOr’, ‘PuRd’,
                                   # ‘Purples’, ‘RdBu’, ‘RdGy’, ‘RdPu’, ‘RdYlBu’, ‘RdYlGn’, ‘Reds’, ‘Set1’, ‘Set2’, ‘Set3’, ‘Spectral’,
                                   # ‘Wistia’, ‘YlGn’, ‘YlGnBu’, ‘YlOrBr’, ‘YlOrRd’, ‘afmhot’, ‘autumn’, ‘binary’, ‘bone’, ‘brg’, ‘bwr’,
                                   # ‘cividis’, ‘cool’, ‘coolwarm’, ‘copper’, ‘cubehelix’, ‘flag’, ‘gist_earth’, ‘gist_gray’, ‘gist_heat’,
                                   # ‘gist_ncar’, ‘gist_rainbow’, ‘gist_stern’, ‘gist_yarg’, ‘gnuplot’, ‘gnuplot2’, ‘gray’, ‘hot’, ‘hsv’,
                                   # ‘icefire’, ‘inferno’, ‘jet’, ‘magma’, ‘mako’, ‘nipy_spectral’, ‘ocean’, ‘pink’, ‘plasma’, ‘prism’,
                                   # ‘rainbow’, ‘rocket’, ‘seismic’, ‘spring’, ‘summer’, ‘tab10’, ‘tab20’, ‘tab20b’, ‘tab20c’, ‘terrain’,
                                   # ‘twilight’, ‘twilight_shifted’, ‘viridis’, ‘vlag’, ‘winter’



### 11. GATK variant calling
